/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V0WorkspaceRouteImport } from './routes/v0-workspace'
import { Route as V0SolutionsRouteImport } from './routes/v0-solutions'
import { Route as V0MessagesRouteImport } from './routes/v0-messages'
import { Route as V0DemoRouteImport } from './routes/v0-demo'
import { Route as TdFollowupsRouteImport } from './routes/td-followups'
import { Route as SupplierRouteImport } from './routes/supplier'
import { Route as MRouteImport } from './routes/m'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierIndexRouteImport } from './routes/supplier.index'
import { Route as MIndexRouteImport } from './routes/m.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToolsInsurancePlanRouteImport } from './routes/tools.insurance-plan'
import { Route as ToolsBudgetCalculatorRouteImport } from './routes/tools.budget-calculator'
import { Route as ToolsAnnualPlanRouteImport } from './routes/tools.annual-plan'
import { Route as SupplierWorkspaceRouteImport } from './routes/supplier.workspace'
import { Route as SupplierProposalsRouteImport } from './routes/supplier.proposals'
import { Route as SupplierOpportunitiesRouteImport } from './routes/supplier.opportunities'
import { Route as SupplierLoginRouteImport } from './routes/supplier.login'
import { Route as SupplierLeadsRouteImport } from './routes/supplier.leads'
import { Route as SupplierFollowupsRouteImport } from './routes/supplier.followups'
import { Route as SupplierFeedbackRouteImport } from './routes/supplier.feedback'
import { Route as SupplierArtistsRouteImport } from './routes/supplier.artists'
import { Route as PProposalIdRouteImport } from './routes/p/$proposalId'
import { Route as MSubmitRouteImport } from './routes/m.submit'
import { Route as MMessagesRouteImport } from './routes/m.messages'
import { Route as MMeRouteImport } from './routes/m.me'
import { Route as MDiscoverRouteImport } from './routes/m.discover'
import { Route as AgentSolutionsRouteImport } from './routes/agent.solutions'
import { Route as AgentRequestsRouteImport } from './routes/agent.requests'
import { Route as AgentMessagesRouteImport } from './routes/agent.messages'
import { Route as AgentLoginRouteImport } from './routes/agent.login'
import { Route as AgentAssistantRouteImport } from './routes/agent.assistant'
import { Route as AdminSkuRouteImport } from './routes/admin.sku'
import { Route as AdminRbacRouteImport } from './routes/admin.rbac'
import { Route as AdminPromptsRouteImport } from './routes/admin.prompts'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLabelingRouteImport } from './routes/admin.labeling'
import { Route as AdminDictRouteImport } from './routes/admin.dict'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminArtistsRouteImport } from './routes/admin.artists'
import { Route as AdminAiFeedbackRouteImport } from './routes/admin.ai-feedback'
import { Route as AdminAgenciesRouteImport } from './routes/admin.agencies'
import { Route as SupplierQuotationsIndexRouteImport } from './routes/supplier.quotations.index'
import { Route as SupplierQuotationsIdRouteImport } from './routes/supplier.quotations.$id'
import { Route as SupplierProposalsIdRouteImport } from './routes/supplier.proposals.$id'
import { Route as SupplierOpportunitiesIdRouteImport } from './routes/supplier.opportunities.$id'
import { Route as SupplierLeadsIdRouteImport } from './routes/supplier.leads.$id'
import { Route as AgentQuotationsIdRouteImport } from './routes/agent.quotations.$id'

const V0WorkspaceRoute = V0WorkspaceRouteImport.update({
  id: '/v0-workspace',
  path: '/v0-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const V0SolutionsRoute = V0SolutionsRouteImport.update({
  id: '/v0-solutions',
  path: '/v0-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const V0MessagesRoute = V0MessagesRouteImport.update({
  id: '/v0-messages',
  path: '/v0-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const V0DemoRoute = V0DemoRouteImport.update({
  id: '/v0-demo',
  path: '/v0-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const TdFollowupsRoute = TdFollowupsRouteImport.update({
  id: '/td-followups',
  path: '/td-followups',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierRoute = SupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierIndexRoute = SupplierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierRoute,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRoute,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ToolsInsurancePlanRoute = ToolsInsurancePlanRouteImport.update({
  id: '/tools/insurance-plan',
  path: '/tools/insurance-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBudgetCalculatorRoute = ToolsBudgetCalculatorRouteImport.update({
  id: '/tools/budget-calculator',
  path: '/tools/budget-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAnnualPlanRoute = ToolsAnnualPlanRouteImport.update({
  id: '/tools/annual-plan',
  path: '/tools/annual-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierWorkspaceRoute = SupplierWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierProposalsRoute = SupplierProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierOpportunitiesRoute = SupplierOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierLoginRoute = SupplierLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierLeadsRoute = SupplierLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierFollowupsRoute = SupplierFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierFeedbackRoute = SupplierFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierArtistsRoute = SupplierArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => SupplierRoute,
} as any)
const PProposalIdRoute = PProposalIdRouteImport.update({
  id: '/p/$proposalId',
  path: '/p/$proposalId',
  getParentRoute: () => rootRouteImport,
} as any)
const MSubmitRoute = MSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => MRoute,
} as any)
const MMessagesRoute = MMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MRoute,
} as any)
const MMeRoute = MMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => MRoute,
} as any)
const MDiscoverRoute = MDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => MRoute,
} as any)
const AgentSolutionsRoute = AgentSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => AgentRoute,
} as any)
const AgentRequestsRoute = AgentRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMessagesRoute = AgentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AgentRoute,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAssistantRoute = AgentAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AgentRoute,
} as any)
const AdminSkuRoute = AdminSkuRouteImport.update({
  id: '/sku',
  path: '/sku',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRbacRoute = AdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromptsRoute = AdminPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLabelingRoute = AdminLabelingRouteImport.update({
  id: '/labeling',
  path: '/labeling',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDictRoute = AdminDictRouteImport.update({
  id: '/dict',
  path: '/dict',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistsRoute = AdminArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiFeedbackRoute = AdminAiFeedbackRouteImport.update({
  id: '/ai-feedback',
  path: '/ai-feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgenciesRoute = AdminAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AdminRoute,
} as any)
const SupplierQuotationsIndexRoute = SupplierQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierQuotationsIdRoute = SupplierQuotationsIdRouteImport.update({
  id: '/quotations/$id',
  path: '/quotations/$id',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierProposalsIdRoute = SupplierProposalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SupplierProposalsRoute,
} as any)
const SupplierOpportunitiesIdRoute = SupplierOpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SupplierOpportunitiesRoute,
} as any)
const SupplierLeadsIdRoute = SupplierLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SupplierLeadsRoute,
} as any)
const AgentQuotationsIdRoute = AgentQuotationsIdRouteImport.update({
  id: '/quotations/$id',
  path: '/quotations/$id',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/m': typeof MRouteWithChildren
  '/supplier': typeof SupplierRouteWithChildren
  '/td-followups': typeof TdFollowupsRoute
  '/v0-demo': typeof V0DemoRoute
  '/v0-messages': typeof V0MessagesRoute
  '/v0-solutions': typeof V0SolutionsRoute
  '/v0-workspace': typeof V0WorkspaceRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/ai-feedback': typeof AdminAiFeedbackRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dict': typeof AdminDictRoute
  '/admin/labeling': typeof AdminLabelingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/sku': typeof AdminSkuRoute
  '/agent/assistant': typeof AgentAssistantRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/requests': typeof AgentRequestsRoute
  '/agent/solutions': typeof AgentSolutionsRoute
  '/m/discover': typeof MDiscoverRoute
  '/m/me': typeof MMeRoute
  '/m/messages': typeof MMessagesRoute
  '/m/submit': typeof MSubmitRoute
  '/p/$proposalId': typeof PProposalIdRoute
  '/supplier/artists': typeof SupplierArtistsRoute
  '/supplier/feedback': typeof SupplierFeedbackRoute
  '/supplier/followups': typeof SupplierFollowupsRoute
  '/supplier/leads': typeof SupplierLeadsRouteWithChildren
  '/supplier/login': typeof SupplierLoginRoute
  '/supplier/opportunities': typeof SupplierOpportunitiesRouteWithChildren
  '/supplier/proposals': typeof SupplierProposalsRouteWithChildren
  '/supplier/workspace': typeof SupplierWorkspaceRoute
  '/tools/annual-plan': typeof ToolsAnnualPlanRoute
  '/tools/budget-calculator': typeof ToolsBudgetCalculatorRoute
  '/tools/insurance-plan': typeof ToolsInsurancePlanRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/m/': typeof MIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/agent/quotations/$id': typeof AgentQuotationsIdRoute
  '/supplier/leads/$id': typeof SupplierLeadsIdRoute
  '/supplier/opportunities/$id': typeof SupplierOpportunitiesIdRoute
  '/supplier/proposals/$id': typeof SupplierProposalsIdRoute
  '/supplier/quotations/$id': typeof SupplierQuotationsIdRoute
  '/supplier/quotations/': typeof SupplierQuotationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/td-followups': typeof TdFollowupsRoute
  '/v0-demo': typeof V0DemoRoute
  '/v0-messages': typeof V0MessagesRoute
  '/v0-solutions': typeof V0SolutionsRoute
  '/v0-workspace': typeof V0WorkspaceRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/ai-feedback': typeof AdminAiFeedbackRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dict': typeof AdminDictRoute
  '/admin/labeling': typeof AdminLabelingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/sku': typeof AdminSkuRoute
  '/agent/assistant': typeof AgentAssistantRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/requests': typeof AgentRequestsRoute
  '/agent/solutions': typeof AgentSolutionsRoute
  '/m/discover': typeof MDiscoverRoute
  '/m/me': typeof MMeRoute
  '/m/messages': typeof MMessagesRoute
  '/m/submit': typeof MSubmitRoute
  '/p/$proposalId': typeof PProposalIdRoute
  '/supplier/artists': typeof SupplierArtistsRoute
  '/supplier/feedback': typeof SupplierFeedbackRoute
  '/supplier/followups': typeof SupplierFollowupsRoute
  '/supplier/leads': typeof SupplierLeadsRouteWithChildren
  '/supplier/login': typeof SupplierLoginRoute
  '/supplier/opportunities': typeof SupplierOpportunitiesRouteWithChildren
  '/supplier/proposals': typeof SupplierProposalsRouteWithChildren
  '/supplier/workspace': typeof SupplierWorkspaceRoute
  '/tools/annual-plan': typeof ToolsAnnualPlanRoute
  '/tools/budget-calculator': typeof ToolsBudgetCalculatorRoute
  '/tools/insurance-plan': typeof ToolsInsurancePlanRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/m': typeof MIndexRoute
  '/supplier': typeof SupplierIndexRoute
  '/agent/quotations/$id': typeof AgentQuotationsIdRoute
  '/supplier/leads/$id': typeof SupplierLeadsIdRoute
  '/supplier/opportunities/$id': typeof SupplierOpportunitiesIdRoute
  '/supplier/proposals/$id': typeof SupplierProposalsIdRoute
  '/supplier/quotations/$id': typeof SupplierQuotationsIdRoute
  '/supplier/quotations': typeof SupplierQuotationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/m': typeof MRouteWithChildren
  '/supplier': typeof SupplierRouteWithChildren
  '/td-followups': typeof TdFollowupsRoute
  '/v0-demo': typeof V0DemoRoute
  '/v0-messages': typeof V0MessagesRoute
  '/v0-solutions': typeof V0SolutionsRoute
  '/v0-workspace': typeof V0WorkspaceRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/ai-feedback': typeof AdminAiFeedbackRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dict': typeof AdminDictRoute
  '/admin/labeling': typeof AdminLabelingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/sku': typeof AdminSkuRoute
  '/agent/assistant': typeof AgentAssistantRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/requests': typeof AgentRequestsRoute
  '/agent/solutions': typeof AgentSolutionsRoute
  '/m/discover': typeof MDiscoverRoute
  '/m/me': typeof MMeRoute
  '/m/messages': typeof MMessagesRoute
  '/m/submit': typeof MSubmitRoute
  '/p/$proposalId': typeof PProposalIdRoute
  '/supplier/artists': typeof SupplierArtistsRoute
  '/supplier/feedback': typeof SupplierFeedbackRoute
  '/supplier/followups': typeof SupplierFollowupsRoute
  '/supplier/leads': typeof SupplierLeadsRouteWithChildren
  '/supplier/login': typeof SupplierLoginRoute
  '/supplier/opportunities': typeof SupplierOpportunitiesRouteWithChildren
  '/supplier/proposals': typeof SupplierProposalsRouteWithChildren
  '/supplier/workspace': typeof SupplierWorkspaceRoute
  '/tools/annual-plan': typeof ToolsAnnualPlanRoute
  '/tools/budget-calculator': typeof ToolsBudgetCalculatorRoute
  '/tools/insurance-plan': typeof ToolsInsurancePlanRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/m/': typeof MIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/agent/quotations/$id': typeof AgentQuotationsIdRoute
  '/supplier/leads/$id': typeof SupplierLeadsIdRoute
  '/supplier/opportunities/$id': typeof SupplierOpportunitiesIdRoute
  '/supplier/proposals/$id': typeof SupplierProposalsIdRoute
  '/supplier/quotations/$id': typeof SupplierQuotationsIdRoute
  '/supplier/quotations/': typeof SupplierQuotationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/m'
    | '/supplier'
    | '/td-followups'
    | '/v0-demo'
    | '/v0-messages'
    | '/v0-solutions'
    | '/v0-workspace'
    | '/admin/agencies'
    | '/admin/ai-feedback'
    | '/admin/artists'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/dict'
    | '/admin/labeling'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/prompts'
    | '/admin/rbac'
    | '/admin/sku'
    | '/agent/assistant'
    | '/agent/login'
    | '/agent/messages'
    | '/agent/requests'
    | '/agent/solutions'
    | '/m/discover'
    | '/m/me'
    | '/m/messages'
    | '/m/submit'
    | '/p/$proposalId'
    | '/supplier/artists'
    | '/supplier/feedback'
    | '/supplier/followups'
    | '/supplier/leads'
    | '/supplier/login'
    | '/supplier/opportunities'
    | '/supplier/proposals'
    | '/supplier/workspace'
    | '/tools/annual-plan'
    | '/tools/budget-calculator'
    | '/tools/insurance-plan'
    | '/admin/'
    | '/agent/'
    | '/m/'
    | '/supplier/'
    | '/agent/quotations/$id'
    | '/supplier/leads/$id'
    | '/supplier/opportunities/$id'
    | '/supplier/proposals/$id'
    | '/supplier/quotations/$id'
    | '/supplier/quotations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/td-followups'
    | '/v0-demo'
    | '/v0-messages'
    | '/v0-solutions'
    | '/v0-workspace'
    | '/admin/agencies'
    | '/admin/ai-feedback'
    | '/admin/artists'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/dict'
    | '/admin/labeling'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/prompts'
    | '/admin/rbac'
    | '/admin/sku'
    | '/agent/assistant'
    | '/agent/login'
    | '/agent/messages'
    | '/agent/requests'
    | '/agent/solutions'
    | '/m/discover'
    | '/m/me'
    | '/m/messages'
    | '/m/submit'
    | '/p/$proposalId'
    | '/supplier/artists'
    | '/supplier/feedback'
    | '/supplier/followups'
    | '/supplier/leads'
    | '/supplier/login'
    | '/supplier/opportunities'
    | '/supplier/proposals'
    | '/supplier/workspace'
    | '/tools/annual-plan'
    | '/tools/budget-calculator'
    | '/tools/insurance-plan'
    | '/admin'
    | '/agent'
    | '/m'
    | '/supplier'
    | '/agent/quotations/$id'
    | '/supplier/leads/$id'
    | '/supplier/opportunities/$id'
    | '/supplier/proposals/$id'
    | '/supplier/quotations/$id'
    | '/supplier/quotations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/m'
    | '/supplier'
    | '/td-followups'
    | '/v0-demo'
    | '/v0-messages'
    | '/v0-solutions'
    | '/v0-workspace'
    | '/admin/agencies'
    | '/admin/ai-feedback'
    | '/admin/artists'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/dict'
    | '/admin/labeling'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/prompts'
    | '/admin/rbac'
    | '/admin/sku'
    | '/agent/assistant'
    | '/agent/login'
    | '/agent/messages'
    | '/agent/requests'
    | '/agent/solutions'
    | '/m/discover'
    | '/m/me'
    | '/m/messages'
    | '/m/submit'
    | '/p/$proposalId'
    | '/supplier/artists'
    | '/supplier/feedback'
    | '/supplier/followups'
    | '/supplier/leads'
    | '/supplier/login'
    | '/supplier/opportunities'
    | '/supplier/proposals'
    | '/supplier/workspace'
    | '/tools/annual-plan'
    | '/tools/budget-calculator'
    | '/tools/insurance-plan'
    | '/admin/'
    | '/agent/'
    | '/m/'
    | '/supplier/'
    | '/agent/quotations/$id'
    | '/supplier/leads/$id'
    | '/supplier/opportunities/$id'
    | '/supplier/proposals/$id'
    | '/supplier/quotations/$id'
    | '/supplier/quotations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  MRoute: typeof MRouteWithChildren
  SupplierRoute: typeof SupplierRouteWithChildren
  TdFollowupsRoute: typeof TdFollowupsRoute
  V0DemoRoute: typeof V0DemoRoute
  V0MessagesRoute: typeof V0MessagesRoute
  V0SolutionsRoute: typeof V0SolutionsRoute
  V0WorkspaceRoute: typeof V0WorkspaceRoute
  PProposalIdRoute: typeof PProposalIdRoute
  ToolsAnnualPlanRoute: typeof ToolsAnnualPlanRoute
  ToolsBudgetCalculatorRoute: typeof ToolsBudgetCalculatorRoute
  ToolsInsurancePlanRoute: typeof ToolsInsurancePlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v0-workspace': {
      id: '/v0-workspace'
      path: '/v0-workspace'
      fullPath: '/v0-workspace'
      preLoaderRoute: typeof V0WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v0-solutions': {
      id: '/v0-solutions'
      path: '/v0-solutions'
      fullPath: '/v0-solutions'
      preLoaderRoute: typeof V0SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v0-messages': {
      id: '/v0-messages'
      path: '/v0-messages'
      fullPath: '/v0-messages'
      preLoaderRoute: typeof V0MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v0-demo': {
      id: '/v0-demo'
      path: '/v0-demo'
      fullPath: '/v0-demo'
      preLoaderRoute: typeof V0DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/td-followups': {
      id: '/td-followups'
      path: '/td-followups'
      fullPath: '/td-followups'
      preLoaderRoute: typeof TdFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier': {
      id: '/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof SupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/': {
      id: '/supplier/'
      path: '/'
      fullPath: '/supplier/'
      preLoaderRoute: typeof SupplierIndexRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tools/insurance-plan': {
      id: '/tools/insurance-plan'
      path: '/tools/insurance-plan'
      fullPath: '/tools/insurance-plan'
      preLoaderRoute: typeof ToolsInsurancePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/budget-calculator': {
      id: '/tools/budget-calculator'
      path: '/tools/budget-calculator'
      fullPath: '/tools/budget-calculator'
      preLoaderRoute: typeof ToolsBudgetCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/annual-plan': {
      id: '/tools/annual-plan'
      path: '/tools/annual-plan'
      fullPath: '/tools/annual-plan'
      preLoaderRoute: typeof ToolsAnnualPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/workspace': {
      id: '/supplier/workspace'
      path: '/workspace'
      fullPath: '/supplier/workspace'
      preLoaderRoute: typeof SupplierWorkspaceRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/proposals': {
      id: '/supplier/proposals'
      path: '/proposals'
      fullPath: '/supplier/proposals'
      preLoaderRoute: typeof SupplierProposalsRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/opportunities': {
      id: '/supplier/opportunities'
      path: '/opportunities'
      fullPath: '/supplier/opportunities'
      preLoaderRoute: typeof SupplierOpportunitiesRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/login': {
      id: '/supplier/login'
      path: '/login'
      fullPath: '/supplier/login'
      preLoaderRoute: typeof SupplierLoginRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/leads': {
      id: '/supplier/leads'
      path: '/leads'
      fullPath: '/supplier/leads'
      preLoaderRoute: typeof SupplierLeadsRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/followups': {
      id: '/supplier/followups'
      path: '/followups'
      fullPath: '/supplier/followups'
      preLoaderRoute: typeof SupplierFollowupsRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/feedback': {
      id: '/supplier/feedback'
      path: '/feedback'
      fullPath: '/supplier/feedback'
      preLoaderRoute: typeof SupplierFeedbackRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/artists': {
      id: '/supplier/artists'
      path: '/artists'
      fullPath: '/supplier/artists'
      preLoaderRoute: typeof SupplierArtistsRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/p/$proposalId': {
      id: '/p/$proposalId'
      path: '/p/$proposalId'
      fullPath: '/p/$proposalId'
      preLoaderRoute: typeof PProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/submit': {
      id: '/m/submit'
      path: '/submit'
      fullPath: '/m/submit'
      preLoaderRoute: typeof MSubmitRouteImport
      parentRoute: typeof MRoute
    }
    '/m/messages': {
      id: '/m/messages'
      path: '/messages'
      fullPath: '/m/messages'
      preLoaderRoute: typeof MMessagesRouteImport
      parentRoute: typeof MRoute
    }
    '/m/me': {
      id: '/m/me'
      path: '/me'
      fullPath: '/m/me'
      preLoaderRoute: typeof MMeRouteImport
      parentRoute: typeof MRoute
    }
    '/m/discover': {
      id: '/m/discover'
      path: '/discover'
      fullPath: '/m/discover'
      preLoaderRoute: typeof MDiscoverRouteImport
      parentRoute: typeof MRoute
    }
    '/agent/solutions': {
      id: '/agent/solutions'
      path: '/solutions'
      fullPath: '/agent/solutions'
      preLoaderRoute: typeof AgentSolutionsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/requests': {
      id: '/agent/requests'
      path: '/requests'
      fullPath: '/agent/requests'
      preLoaderRoute: typeof AgentRequestsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/messages': {
      id: '/agent/messages'
      path: '/messages'
      fullPath: '/agent/messages'
      preLoaderRoute: typeof AgentMessagesRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/login': {
      id: '/agent/login'
      path: '/login'
      fullPath: '/agent/login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/assistant': {
      id: '/agent/assistant'
      path: '/assistant'
      fullPath: '/agent/assistant'
      preLoaderRoute: typeof AgentAssistantRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/sku': {
      id: '/admin/sku'
      path: '/sku'
      fullPath: '/admin/sku'
      preLoaderRoute: typeof AdminSkuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rbac': {
      id: '/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AdminRbacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prompts': {
      id: '/admin/prompts'
      path: '/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AdminPromptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/labeling': {
      id: '/admin/labeling'
      path: '/labeling'
      fullPath: '/admin/labeling'
      preLoaderRoute: typeof AdminLabelingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dict': {
      id: '/admin/dict'
      path: '/dict'
      fullPath: '/admin/dict'
      preLoaderRoute: typeof AdminDictRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artists': {
      id: '/admin/artists'
      path: '/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminArtistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-feedback': {
      id: '/admin/ai-feedback'
      path: '/ai-feedback'
      fullPath: '/admin/ai-feedback'
      preLoaderRoute: typeof AdminAiFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agencies': {
      id: '/admin/agencies'
      path: '/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AdminAgenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/supplier/quotations/': {
      id: '/supplier/quotations/'
      path: '/quotations'
      fullPath: '/supplier/quotations/'
      preLoaderRoute: typeof SupplierQuotationsIndexRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/quotations/$id': {
      id: '/supplier/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/supplier/quotations/$id'
      preLoaderRoute: typeof SupplierQuotationsIdRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/proposals/$id': {
      id: '/supplier/proposals/$id'
      path: '/$id'
      fullPath: '/supplier/proposals/$id'
      preLoaderRoute: typeof SupplierProposalsIdRouteImport
      parentRoute: typeof SupplierProposalsRoute
    }
    '/supplier/opportunities/$id': {
      id: '/supplier/opportunities/$id'
      path: '/$id'
      fullPath: '/supplier/opportunities/$id'
      preLoaderRoute: typeof SupplierOpportunitiesIdRouteImport
      parentRoute: typeof SupplierOpportunitiesRoute
    }
    '/supplier/leads/$id': {
      id: '/supplier/leads/$id'
      path: '/$id'
      fullPath: '/supplier/leads/$id'
      preLoaderRoute: typeof SupplierLeadsIdRouteImport
      parentRoute: typeof SupplierLeadsRoute
    }
    '/agent/quotations/$id': {
      id: '/agent/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/agent/quotations/$id'
      preLoaderRoute: typeof AgentQuotationsIdRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgenciesRoute: typeof AdminAgenciesRoute
  AdminAiFeedbackRoute: typeof AdminAiFeedbackRoute
  AdminArtistsRoute: typeof AdminArtistsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDictRoute: typeof AdminDictRoute
  AdminLabelingRoute: typeof AdminLabelingRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPromptsRoute: typeof AdminPromptsRoute
  AdminRbacRoute: typeof AdminRbacRoute
  AdminSkuRoute: typeof AdminSkuRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgenciesRoute: AdminAgenciesRoute,
  AdminAiFeedbackRoute: AdminAiFeedbackRoute,
  AdminArtistsRoute: AdminArtistsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDictRoute: AdminDictRoute,
  AdminLabelingRoute: AdminLabelingRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPromptsRoute: AdminPromptsRoute,
  AdminRbacRoute: AdminRbacRoute,
  AdminSkuRoute: AdminSkuRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentRouteChildren {
  AgentAssistantRoute: typeof AgentAssistantRoute
  AgentLoginRoute: typeof AgentLoginRoute
  AgentMessagesRoute: typeof AgentMessagesRoute
  AgentRequestsRoute: typeof AgentRequestsRoute
  AgentSolutionsRoute: typeof AgentSolutionsRoute
  AgentIndexRoute: typeof AgentIndexRoute
  AgentQuotationsIdRoute: typeof AgentQuotationsIdRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAssistantRoute: AgentAssistantRoute,
  AgentLoginRoute: AgentLoginRoute,
  AgentMessagesRoute: AgentMessagesRoute,
  AgentRequestsRoute: AgentRequestsRoute,
  AgentSolutionsRoute: AgentSolutionsRoute,
  AgentIndexRoute: AgentIndexRoute,
  AgentQuotationsIdRoute: AgentQuotationsIdRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface MRouteChildren {
  MDiscoverRoute: typeof MDiscoverRoute
  MMeRoute: typeof MMeRoute
  MMessagesRoute: typeof MMessagesRoute
  MSubmitRoute: typeof MSubmitRoute
  MIndexRoute: typeof MIndexRoute
}

const MRouteChildren: MRouteChildren = {
  MDiscoverRoute: MDiscoverRoute,
  MMeRoute: MMeRoute,
  MMessagesRoute: MMessagesRoute,
  MSubmitRoute: MSubmitRoute,
  MIndexRoute: MIndexRoute,
}

const MRouteWithChildren = MRoute._addFileChildren(MRouteChildren)

interface SupplierLeadsRouteChildren {
  SupplierLeadsIdRoute: typeof SupplierLeadsIdRoute
}

const SupplierLeadsRouteChildren: SupplierLeadsRouteChildren = {
  SupplierLeadsIdRoute: SupplierLeadsIdRoute,
}

const SupplierLeadsRouteWithChildren = SupplierLeadsRoute._addFileChildren(
  SupplierLeadsRouteChildren,
)

interface SupplierOpportunitiesRouteChildren {
  SupplierOpportunitiesIdRoute: typeof SupplierOpportunitiesIdRoute
}

const SupplierOpportunitiesRouteChildren: SupplierOpportunitiesRouteChildren = {
  SupplierOpportunitiesIdRoute: SupplierOpportunitiesIdRoute,
}

const SupplierOpportunitiesRouteWithChildren =
  SupplierOpportunitiesRoute._addFileChildren(
    SupplierOpportunitiesRouteChildren,
  )

interface SupplierProposalsRouteChildren {
  SupplierProposalsIdRoute: typeof SupplierProposalsIdRoute
}

const SupplierProposalsRouteChildren: SupplierProposalsRouteChildren = {
  SupplierProposalsIdRoute: SupplierProposalsIdRoute,
}

const SupplierProposalsRouteWithChildren =
  SupplierProposalsRoute._addFileChildren(SupplierProposalsRouteChildren)

interface SupplierRouteChildren {
  SupplierArtistsRoute: typeof SupplierArtistsRoute
  SupplierFeedbackRoute: typeof SupplierFeedbackRoute
  SupplierFollowupsRoute: typeof SupplierFollowupsRoute
  SupplierLeadsRoute: typeof SupplierLeadsRouteWithChildren
  SupplierLoginRoute: typeof SupplierLoginRoute
  SupplierOpportunitiesRoute: typeof SupplierOpportunitiesRouteWithChildren
  SupplierProposalsRoute: typeof SupplierProposalsRouteWithChildren
  SupplierWorkspaceRoute: typeof SupplierWorkspaceRoute
  SupplierIndexRoute: typeof SupplierIndexRoute
  SupplierQuotationsIdRoute: typeof SupplierQuotationsIdRoute
  SupplierQuotationsIndexRoute: typeof SupplierQuotationsIndexRoute
}

const SupplierRouteChildren: SupplierRouteChildren = {
  SupplierArtistsRoute: SupplierArtistsRoute,
  SupplierFeedbackRoute: SupplierFeedbackRoute,
  SupplierFollowupsRoute: SupplierFollowupsRoute,
  SupplierLeadsRoute: SupplierLeadsRouteWithChildren,
  SupplierLoginRoute: SupplierLoginRoute,
  SupplierOpportunitiesRoute: SupplierOpportunitiesRouteWithChildren,
  SupplierProposalsRoute: SupplierProposalsRouteWithChildren,
  SupplierWorkspaceRoute: SupplierWorkspaceRoute,
  SupplierIndexRoute: SupplierIndexRoute,
  SupplierQuotationsIdRoute: SupplierQuotationsIdRoute,
  SupplierQuotationsIndexRoute: SupplierQuotationsIndexRoute,
}

const SupplierRouteWithChildren = SupplierRoute._addFileChildren(
  SupplierRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  MRoute: MRouteWithChildren,
  SupplierRoute: SupplierRouteWithChildren,
  TdFollowupsRoute: TdFollowupsRoute,
  V0DemoRoute: V0DemoRoute,
  V0MessagesRoute: V0MessagesRoute,
  V0SolutionsRoute: V0SolutionsRoute,
  V0WorkspaceRoute: V0WorkspaceRoute,
  PProposalIdRoute: PProposalIdRoute,
  ToolsAnnualPlanRoute: ToolsAnnualPlanRoute,
  ToolsBudgetCalculatorRoute: ToolsBudgetCalculatorRoute,
  ToolsInsurancePlanRoute: ToolsInsurancePlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
