/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnapshotRouteImport } from './routes/snapshot'
import { Route as MediaLibraryRouteImport } from './routes/media-library'
import { Route as MRouteImport } from './routes/m'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as GapChecklistRouteImport } from './routes/gap-checklist'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ActorIndexRouteImport } from './routes/actor.index'
import { Route as TenantProgramsRouteImport } from './routes/tenant.programs'
import { Route as TenantPartnersRouteImport } from './routes/tenant.partners'
import { Route as TenantExecutionRouteImport } from './routes/tenant.execution'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as H5ActorRouteImport } from './routes/h5.actor'
import { Route as AgentMemoryRouteImport } from './routes/agent.memory'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminIncidentsRouteImport } from './routes/admin.incidents'
import { Route as AdminAttributionRouteImport } from './routes/admin.attribution'
import { Route as ActorServicesRouteImport } from './routes/actor.services'
import { Route as ActorPreferencesRouteImport } from './routes/actor.preferences'
import { Route as ActorDisputesRouteImport } from './routes/actor.disputes'
import { Route as ActorCalendarRouteImport } from './routes/actor.calendar'
import { Route as AccountDataRouteImport } from './routes/account.data'
import { Route as TenantSettlementIndexRouteImport } from './routes/tenant.settlement.index'
import { Route as TenantServiceProductsIndexRouteImport } from './routes/tenant.service-products.index'
import { Route as TenantOrdersIndexRouteImport } from './routes/tenant.orders.index'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects.$id.index'
import { Route as DiscoverServiceProductsIndexRouteImport } from './routes/discover.service-products.index'
import { Route as DiscoverProgramsIndexRouteImport } from './routes/discover.programs.index'
import { Route as DiscoverCasesIndexRouteImport } from './routes/discover.cases.index'
import { Route as DiscoverActorsIndexRouteImport } from './routes/discover.actors.index'
import { Route as TenantSettlementMonthRouteImport } from './routes/tenant.settlement.$month'
import { Route as TenantServiceProductsFeedbackRouteImport } from './routes/tenant.service-products.feedback'
import { Route as TenantOrdersIdRouteImport } from './routes/tenant.orders.$id'
import { Route as TenantOpportunitiesIdRouteImport } from './routes/tenant.opportunities.$id'
import { Route as ProjectsIdWaitingRouteImport } from './routes/projects.$id.waiting'
import { Route as ProjectsIdUnderstandRouteImport } from './routes/projects.$id.understand'
import { Route as ProjectsIdTeamRouteImport } from './routes/projects.$id.team'
import { Route as ProjectsIdShareRouteImport } from './routes/projects.$id.share'
import { Route as ProjectsIdReviewRouteImport } from './routes/projects.$id.review'
import { Route as ProjectsIdReuseRouteImport } from './routes/projects.$id.reuse'
import { Route as ProjectsIdRetrospectiveRouteImport } from './routes/projects.$id.retrospective'
import { Route as ProjectsIdQuoteRouteImport } from './routes/projects.$id.quote'
import { Route as ProjectsIdPlansRouteImport } from './routes/projects.$id.plans'
import { Route as ProjectsIdOutcomeRouteImport } from './routes/projects.$id.outcome'
import { Route as ProjectsIdMessagesRouteImport } from './routes/projects.$id.messages'
import { Route as ProjectsIdIncidentsRouteImport } from './routes/projects.$id.incidents'
import { Route as ProjectsIdDecisionRouteImport } from './routes/projects.$id.decision'
import { Route as ProjectsIdDealRouteImport } from './routes/projects.$id.deal'
import { Route as ProjectsIdChangesRouteImport } from './routes/projects.$id.changes'
import { Route as PlansIdPublicRouteImport } from './routes/plans.$id.public'
import { Route as H5TenantMsaRouteImport } from './routes/h5.tenant.msa'
import { Route as DiscoverTenantsIdRouteImport } from './routes/discover.tenants.$id'
import { Route as DiscoverServiceProductsCompareRouteImport } from './routes/discover.service-products.compare'
import { Route as DiscoverProgramsIdRouteImport } from './routes/discover.programs.$id'
import { Route as DiscoverCasesCompareRouteImport } from './routes/discover.cases.compare'
import { Route as DiscoverCasesIdRouteImport } from './routes/discover.cases.$id'
import { Route as DiscoverActorsIdRouteImport } from './routes/discover.actors.$id'
import { Route as AdminTenantsIdRouteImport } from './routes/admin.tenants.$id'
import { Route as AdminArbitrationIdRouteImport } from './routes/admin.arbitration.$id'
import { Route as TenantServiceProductsIdIndexRouteImport } from './routes/tenant.service-products.$id.index'
import { Route as ProjectsIdPaymentsIndexRouteImport } from './routes/projects.$id.payments.index'
import { Route as ProjectsIdExecutionIndexRouteImport } from './routes/projects.$id.execution.index'
import { Route as ProjectsIdContractIndexRouteImport } from './routes/projects.$id.contract.index'
import { Route as ProjectsIdCandidatesIndexRouteImport } from './routes/projects.$id.candidates.index'
import { Route as DiscoverServiceProductsIdIndexRouteImport } from './routes/discover.service-products.$id.index'
import { Route as TenantServiceProductsIdVersionsRouteImport } from './routes/tenant.service-products.$id.versions'
import { Route as ProjectsIdPaymentsSchemeRouteImport } from './routes/projects.$id.payments.scheme'
import { Route as ProjectsIdExecutionHandoffRouteImport } from './routes/projects.$id.execution.handoff'
import { Route as ProjectsIdExecutionAudienceRouteImport } from './routes/projects.$id.execution.audience'
import { Route as ProjectsIdContractTreeRouteImport } from './routes/projects.$id.contract.tree'
import { Route as ProjectsIdContractVoucherIdRouteImport } from './routes/projects.$id.contract.$voucherId'
import { Route as ProjectsIdCandidatesCompareRouteImport } from './routes/projects.$id.candidates.compare'
import { Route as DiscoverServiceProductsIdStartRouteImport } from './routes/discover.service-products.$id.start'
import { Route as DiscoverServiceProductsIdShareRouteImport } from './routes/discover.service-products.$id.share'

const SnapshotRoute = SnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaLibraryRoute = MediaLibraryRouteImport.update({
  id: '/media-library',
  path: '/media-library',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const GapChecklistRoute = GapChecklistRouteImport.update({
  id: '/gap-checklist',
  path: '/gap-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/tenant/',
  path: '/tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorIndexRoute = ActorIndexRouteImport.update({
  id: '/actor/',
  path: '/actor/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantProgramsRoute = TenantProgramsRouteImport.update({
  id: '/tenant/programs',
  path: '/tenant/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantPartnersRoute = TenantPartnersRouteImport.update({
  id: '/tenant/partners',
  path: '/tenant/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantExecutionRoute = TenantExecutionRouteImport.update({
  id: '/tenant/execution',
  path: '/tenant/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const H5ActorRoute = H5ActorRouteImport.update({
  id: '/h5/actor',
  path: '/h5/actor',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMemoryRoute = AgentMemoryRouteImport.update({
  id: '/agent/memory',
  path: '/agent/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIncidentsRoute = AdminIncidentsRouteImport.update({
  id: '/admin/incidents',
  path: '/admin/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttributionRoute = AdminAttributionRouteImport.update({
  id: '/admin/attribution',
  path: '/admin/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorServicesRoute = ActorServicesRouteImport.update({
  id: '/actor/services',
  path: '/actor/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorPreferencesRoute = ActorPreferencesRouteImport.update({
  id: '/actor/preferences',
  path: '/actor/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorDisputesRoute = ActorDisputesRouteImport.update({
  id: '/actor/disputes',
  path: '/actor/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorCalendarRoute = ActorCalendarRouteImport.update({
  id: '/actor/calendar',
  path: '/actor/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDataRoute = AccountDataRouteImport.update({
  id: '/account/data',
  path: '/account/data',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSettlementIndexRoute = TenantSettlementIndexRouteImport.update({
  id: '/tenant/settlement/',
  path: '/tenant/settlement/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantServiceProductsIndexRoute =
  TenantServiceProductsIndexRouteImport.update({
    id: '/tenant/service-products/',
    path: '/tenant/service-products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantOrdersIndexRoute = TenantOrdersIndexRouteImport.update({
  id: '/tenant/orders/',
  path: '/tenant/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const DiscoverServiceProductsIndexRoute =
  DiscoverServiceProductsIndexRouteImport.update({
    id: '/discover/service-products/',
    path: '/discover/service-products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiscoverProgramsIndexRoute = DiscoverProgramsIndexRouteImport.update({
  id: '/discover/programs/',
  path: '/discover/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverCasesIndexRoute = DiscoverCasesIndexRouteImport.update({
  id: '/discover/cases/',
  path: '/discover/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverActorsIndexRoute = DiscoverActorsIndexRouteImport.update({
  id: '/discover/actors/',
  path: '/discover/actors/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSettlementMonthRoute = TenantSettlementMonthRouteImport.update({
  id: '/tenant/settlement/$month',
  path: '/tenant/settlement/$month',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantServiceProductsFeedbackRoute =
  TenantServiceProductsFeedbackRouteImport.update({
    id: '/tenant/service-products/feedback',
    path: '/tenant/service-products/feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantOrdersIdRoute = TenantOrdersIdRouteImport.update({
  id: '/tenant/orders/$id',
  path: '/tenant/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantOpportunitiesIdRoute = TenantOpportunitiesIdRouteImport.update({
  id: '/tenant/opportunities/$id',
  path: '/tenant/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdWaitingRoute = ProjectsIdWaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdUnderstandRoute = ProjectsIdUnderstandRouteImport.update({
  id: '/understand',
  path: '/understand',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdTeamRoute = ProjectsIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdShareRoute = ProjectsIdShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdReviewRoute = ProjectsIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdReuseRoute = ProjectsIdReuseRouteImport.update({
  id: '/reuse',
  path: '/reuse',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdRetrospectiveRoute = ProjectsIdRetrospectiveRouteImport.update({
  id: '/retrospective',
  path: '/retrospective',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdQuoteRoute = ProjectsIdQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdPlansRoute = ProjectsIdPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdOutcomeRoute = ProjectsIdOutcomeRouteImport.update({
  id: '/outcome',
  path: '/outcome',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdMessagesRoute = ProjectsIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdIncidentsRoute = ProjectsIdIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdDecisionRoute = ProjectsIdDecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdDealRoute = ProjectsIdDealRouteImport.update({
  id: '/deal',
  path: '/deal',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdChangesRoute = ProjectsIdChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const PlansIdPublicRoute = PlansIdPublicRouteImport.update({
  id: '/plans/$id/public',
  path: '/plans/$id/public',
  getParentRoute: () => rootRouteImport,
} as any)
const H5TenantMsaRoute = H5TenantMsaRouteImport.update({
  id: '/h5/tenant/msa',
  path: '/h5/tenant/msa',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverTenantsIdRoute = DiscoverTenantsIdRouteImport.update({
  id: '/discover/tenants/$id',
  path: '/discover/tenants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverServiceProductsCompareRoute =
  DiscoverServiceProductsCompareRouteImport.update({
    id: '/discover/service-products/compare',
    path: '/discover/service-products/compare',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiscoverProgramsIdRoute = DiscoverProgramsIdRouteImport.update({
  id: '/discover/programs/$id',
  path: '/discover/programs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverCasesCompareRoute = DiscoverCasesCompareRouteImport.update({
  id: '/discover/cases/compare',
  path: '/discover/cases/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverCasesIdRoute = DiscoverCasesIdRouteImport.update({
  id: '/discover/cases/$id',
  path: '/discover/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverActorsIdRoute = DiscoverActorsIdRouteImport.update({
  id: '/discover/actors/$id',
  path: '/discover/actors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsIdRoute = AdminTenantsIdRouteImport.update({
  id: '/admin/tenants/$id',
  path: '/admin/tenants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArbitrationIdRoute = AdminArbitrationIdRouteImport.update({
  id: '/admin/arbitration/$id',
  path: '/admin/arbitration/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantServiceProductsIdIndexRoute =
  TenantServiceProductsIdIndexRouteImport.update({
    id: '/tenant/service-products/$id/',
    path: '/tenant/service-products/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdPaymentsIndexRoute = ProjectsIdPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdExecutionIndexRoute =
  ProjectsIdExecutionIndexRouteImport.update({
    id: '/execution/',
    path: '/execution/',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdContractIndexRoute = ProjectsIdContractIndexRouteImport.update({
  id: '/contract/',
  path: '/contract/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdCandidatesIndexRoute =
  ProjectsIdCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const DiscoverServiceProductsIdIndexRoute =
  DiscoverServiceProductsIdIndexRouteImport.update({
    id: '/discover/service-products/$id/',
    path: '/discover/service-products/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantServiceProductsIdVersionsRoute =
  TenantServiceProductsIdVersionsRouteImport.update({
    id: '/tenant/service-products/$id/versions',
    path: '/tenant/service-products/$id/versions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdPaymentsSchemeRoute =
  ProjectsIdPaymentsSchemeRouteImport.update({
    id: '/payments/scheme',
    path: '/payments/scheme',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdExecutionHandoffRoute =
  ProjectsIdExecutionHandoffRouteImport.update({
    id: '/execution/handoff',
    path: '/execution/handoff',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdExecutionAudienceRoute =
  ProjectsIdExecutionAudienceRouteImport.update({
    id: '/execution/audience',
    path: '/execution/audience',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdContractTreeRoute = ProjectsIdContractTreeRouteImport.update({
  id: '/contract/tree',
  path: '/contract/tree',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdContractVoucherIdRoute =
  ProjectsIdContractVoucherIdRouteImport.update({
    id: '/contract/$voucherId',
    path: '/contract/$voucherId',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdCandidatesCompareRoute =
  ProjectsIdCandidatesCompareRouteImport.update({
    id: '/candidates/compare',
    path: '/candidates/compare',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const DiscoverServiceProductsIdStartRoute =
  DiscoverServiceProductsIdStartRouteImport.update({
    id: '/discover/service-products/$id/start',
    path: '/discover/service-products/$id/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiscoverServiceProductsIdShareRoute =
  DiscoverServiceProductsIdShareRouteImport.update({
    id: '/discover/service-products/$id/share',
    path: '/discover/service-products/$id/share',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/dev-login': typeof DevLoginRoute
  '/gap-checklist': typeof GapChecklistRoute
  '/guides': typeof GuidesRoute
  '/m': typeof MRoute
  '/media-library': typeof MediaLibraryRoute
  '/snapshot': typeof SnapshotRoute
  '/account/data': typeof AccountDataRoute
  '/actor/calendar': typeof ActorCalendarRoute
  '/actor/disputes': typeof ActorDisputesRoute
  '/actor/preferences': typeof ActorPreferencesRoute
  '/actor/services': typeof ActorServicesRoute
  '/admin/attribution': typeof AdminAttributionRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/agent/memory': typeof AgentMemoryRoute
  '/h5/actor': typeof H5ActorRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/tenant/execution': typeof TenantExecutionRoute
  '/tenant/partners': typeof TenantPartnersRoute
  '/tenant/programs': typeof TenantProgramsRoute
  '/actor/': typeof ActorIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/admin/arbitration/$id': typeof AdminArbitrationIdRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/discover/actors/$id': typeof DiscoverActorsIdRoute
  '/discover/cases/$id': typeof DiscoverCasesIdRoute
  '/discover/cases/compare': typeof DiscoverCasesCompareRoute
  '/discover/programs/$id': typeof DiscoverProgramsIdRoute
  '/discover/service-products/compare': typeof DiscoverServiceProductsCompareRoute
  '/discover/tenants/$id': typeof DiscoverTenantsIdRoute
  '/h5/tenant/msa': typeof H5TenantMsaRoute
  '/plans/$id/public': typeof PlansIdPublicRoute
  '/projects/$id/changes': typeof ProjectsIdChangesRoute
  '/projects/$id/deal': typeof ProjectsIdDealRoute
  '/projects/$id/decision': typeof ProjectsIdDecisionRoute
  '/projects/$id/incidents': typeof ProjectsIdIncidentsRoute
  '/projects/$id/messages': typeof ProjectsIdMessagesRoute
  '/projects/$id/outcome': typeof ProjectsIdOutcomeRoute
  '/projects/$id/plans': typeof ProjectsIdPlansRoute
  '/projects/$id/quote': typeof ProjectsIdQuoteRoute
  '/projects/$id/retrospective': typeof ProjectsIdRetrospectiveRoute
  '/projects/$id/reuse': typeof ProjectsIdReuseRoute
  '/projects/$id/review': typeof ProjectsIdReviewRoute
  '/projects/$id/share': typeof ProjectsIdShareRoute
  '/projects/$id/team': typeof ProjectsIdTeamRoute
  '/projects/$id/understand': typeof ProjectsIdUnderstandRoute
  '/projects/$id/waiting': typeof ProjectsIdWaitingRoute
  '/tenant/opportunities/$id': typeof TenantOpportunitiesIdRoute
  '/tenant/orders/$id': typeof TenantOrdersIdRoute
  '/tenant/service-products/feedback': typeof TenantServiceProductsFeedbackRoute
  '/tenant/settlement/$month': typeof TenantSettlementMonthRoute
  '/discover/actors/': typeof DiscoverActorsIndexRoute
  '/discover/cases/': typeof DiscoverCasesIndexRoute
  '/discover/programs/': typeof DiscoverProgramsIndexRoute
  '/discover/service-products/': typeof DiscoverServiceProductsIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/tenant/orders/': typeof TenantOrdersIndexRoute
  '/tenant/service-products/': typeof TenantServiceProductsIndexRoute
  '/tenant/settlement/': typeof TenantSettlementIndexRoute
  '/discover/service-products/$id/share': typeof DiscoverServiceProductsIdShareRoute
  '/discover/service-products/$id/start': typeof DiscoverServiceProductsIdStartRoute
  '/projects/$id/candidates/compare': typeof ProjectsIdCandidatesCompareRoute
  '/projects/$id/contract/$voucherId': typeof ProjectsIdContractVoucherIdRoute
  '/projects/$id/contract/tree': typeof ProjectsIdContractTreeRoute
  '/projects/$id/execution/audience': typeof ProjectsIdExecutionAudienceRoute
  '/projects/$id/execution/handoff': typeof ProjectsIdExecutionHandoffRoute
  '/projects/$id/payments/scheme': typeof ProjectsIdPaymentsSchemeRoute
  '/tenant/service-products/$id/versions': typeof TenantServiceProductsIdVersionsRoute
  '/discover/service-products/$id/': typeof DiscoverServiceProductsIdIndexRoute
  '/projects/$id/candidates/': typeof ProjectsIdCandidatesIndexRoute
  '/projects/$id/contract/': typeof ProjectsIdContractIndexRoute
  '/projects/$id/execution/': typeof ProjectsIdExecutionIndexRoute
  '/projects/$id/payments/': typeof ProjectsIdPaymentsIndexRoute
  '/tenant/service-products/$id/': typeof TenantServiceProductsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/dev-login': typeof DevLoginRoute
  '/gap-checklist': typeof GapChecklistRoute
  '/guides': typeof GuidesRoute
  '/m': typeof MRoute
  '/media-library': typeof MediaLibraryRoute
  '/snapshot': typeof SnapshotRoute
  '/account/data': typeof AccountDataRoute
  '/actor/calendar': typeof ActorCalendarRoute
  '/actor/disputes': typeof ActorDisputesRoute
  '/actor/preferences': typeof ActorPreferencesRoute
  '/actor/services': typeof ActorServicesRoute
  '/admin/attribution': typeof AdminAttributionRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/agent/memory': typeof AgentMemoryRoute
  '/h5/actor': typeof H5ActorRoute
  '/tenant/execution': typeof TenantExecutionRoute
  '/tenant/partners': typeof TenantPartnersRoute
  '/tenant/programs': typeof TenantProgramsRoute
  '/actor': typeof ActorIndexRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/tenant': typeof TenantIndexRoute
  '/admin/arbitration/$id': typeof AdminArbitrationIdRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/discover/actors/$id': typeof DiscoverActorsIdRoute
  '/discover/cases/$id': typeof DiscoverCasesIdRoute
  '/discover/cases/compare': typeof DiscoverCasesCompareRoute
  '/discover/programs/$id': typeof DiscoverProgramsIdRoute
  '/discover/service-products/compare': typeof DiscoverServiceProductsCompareRoute
  '/discover/tenants/$id': typeof DiscoverTenantsIdRoute
  '/h5/tenant/msa': typeof H5TenantMsaRoute
  '/plans/$id/public': typeof PlansIdPublicRoute
  '/projects/$id/changes': typeof ProjectsIdChangesRoute
  '/projects/$id/deal': typeof ProjectsIdDealRoute
  '/projects/$id/decision': typeof ProjectsIdDecisionRoute
  '/projects/$id/incidents': typeof ProjectsIdIncidentsRoute
  '/projects/$id/messages': typeof ProjectsIdMessagesRoute
  '/projects/$id/outcome': typeof ProjectsIdOutcomeRoute
  '/projects/$id/plans': typeof ProjectsIdPlansRoute
  '/projects/$id/quote': typeof ProjectsIdQuoteRoute
  '/projects/$id/retrospective': typeof ProjectsIdRetrospectiveRoute
  '/projects/$id/reuse': typeof ProjectsIdReuseRoute
  '/projects/$id/review': typeof ProjectsIdReviewRoute
  '/projects/$id/share': typeof ProjectsIdShareRoute
  '/projects/$id/team': typeof ProjectsIdTeamRoute
  '/projects/$id/understand': typeof ProjectsIdUnderstandRoute
  '/projects/$id/waiting': typeof ProjectsIdWaitingRoute
  '/tenant/opportunities/$id': typeof TenantOpportunitiesIdRoute
  '/tenant/orders/$id': typeof TenantOrdersIdRoute
  '/tenant/service-products/feedback': typeof TenantServiceProductsFeedbackRoute
  '/tenant/settlement/$month': typeof TenantSettlementMonthRoute
  '/discover/actors': typeof DiscoverActorsIndexRoute
  '/discover/cases': typeof DiscoverCasesIndexRoute
  '/discover/programs': typeof DiscoverProgramsIndexRoute
  '/discover/service-products': typeof DiscoverServiceProductsIndexRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/tenant/orders': typeof TenantOrdersIndexRoute
  '/tenant/service-products': typeof TenantServiceProductsIndexRoute
  '/tenant/settlement': typeof TenantSettlementIndexRoute
  '/discover/service-products/$id/share': typeof DiscoverServiceProductsIdShareRoute
  '/discover/service-products/$id/start': typeof DiscoverServiceProductsIdStartRoute
  '/projects/$id/candidates/compare': typeof ProjectsIdCandidatesCompareRoute
  '/projects/$id/contract/$voucherId': typeof ProjectsIdContractVoucherIdRoute
  '/projects/$id/contract/tree': typeof ProjectsIdContractTreeRoute
  '/projects/$id/execution/audience': typeof ProjectsIdExecutionAudienceRoute
  '/projects/$id/execution/handoff': typeof ProjectsIdExecutionHandoffRoute
  '/projects/$id/payments/scheme': typeof ProjectsIdPaymentsSchemeRoute
  '/tenant/service-products/$id/versions': typeof TenantServiceProductsIdVersionsRoute
  '/discover/service-products/$id': typeof DiscoverServiceProductsIdIndexRoute
  '/projects/$id/candidates': typeof ProjectsIdCandidatesIndexRoute
  '/projects/$id/contract': typeof ProjectsIdContractIndexRoute
  '/projects/$id/execution': typeof ProjectsIdExecutionIndexRoute
  '/projects/$id/payments': typeof ProjectsIdPaymentsIndexRoute
  '/tenant/service-products/$id': typeof TenantServiceProductsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/dev-login': typeof DevLoginRoute
  '/gap-checklist': typeof GapChecklistRoute
  '/guides': typeof GuidesRoute
  '/m': typeof MRoute
  '/media-library': typeof MediaLibraryRoute
  '/snapshot': typeof SnapshotRoute
  '/account/data': typeof AccountDataRoute
  '/actor/calendar': typeof ActorCalendarRoute
  '/actor/disputes': typeof ActorDisputesRoute
  '/actor/preferences': typeof ActorPreferencesRoute
  '/actor/services': typeof ActorServicesRoute
  '/admin/attribution': typeof AdminAttributionRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/agent/memory': typeof AgentMemoryRoute
  '/h5/actor': typeof H5ActorRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/tenant/execution': typeof TenantExecutionRoute
  '/tenant/partners': typeof TenantPartnersRoute
  '/tenant/programs': typeof TenantProgramsRoute
  '/actor/': typeof ActorIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/admin/arbitration/$id': typeof AdminArbitrationIdRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/discover/actors/$id': typeof DiscoverActorsIdRoute
  '/discover/cases/$id': typeof DiscoverCasesIdRoute
  '/discover/cases/compare': typeof DiscoverCasesCompareRoute
  '/discover/programs/$id': typeof DiscoverProgramsIdRoute
  '/discover/service-products/compare': typeof DiscoverServiceProductsCompareRoute
  '/discover/tenants/$id': typeof DiscoverTenantsIdRoute
  '/h5/tenant/msa': typeof H5TenantMsaRoute
  '/plans/$id/public': typeof PlansIdPublicRoute
  '/projects/$id/changes': typeof ProjectsIdChangesRoute
  '/projects/$id/deal': typeof ProjectsIdDealRoute
  '/projects/$id/decision': typeof ProjectsIdDecisionRoute
  '/projects/$id/incidents': typeof ProjectsIdIncidentsRoute
  '/projects/$id/messages': typeof ProjectsIdMessagesRoute
  '/projects/$id/outcome': typeof ProjectsIdOutcomeRoute
  '/projects/$id/plans': typeof ProjectsIdPlansRoute
  '/projects/$id/quote': typeof ProjectsIdQuoteRoute
  '/projects/$id/retrospective': typeof ProjectsIdRetrospectiveRoute
  '/projects/$id/reuse': typeof ProjectsIdReuseRoute
  '/projects/$id/review': typeof ProjectsIdReviewRoute
  '/projects/$id/share': typeof ProjectsIdShareRoute
  '/projects/$id/team': typeof ProjectsIdTeamRoute
  '/projects/$id/understand': typeof ProjectsIdUnderstandRoute
  '/projects/$id/waiting': typeof ProjectsIdWaitingRoute
  '/tenant/opportunities/$id': typeof TenantOpportunitiesIdRoute
  '/tenant/orders/$id': typeof TenantOrdersIdRoute
  '/tenant/service-products/feedback': typeof TenantServiceProductsFeedbackRoute
  '/tenant/settlement/$month': typeof TenantSettlementMonthRoute
  '/discover/actors/': typeof DiscoverActorsIndexRoute
  '/discover/cases/': typeof DiscoverCasesIndexRoute
  '/discover/programs/': typeof DiscoverProgramsIndexRoute
  '/discover/service-products/': typeof DiscoverServiceProductsIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/tenant/orders/': typeof TenantOrdersIndexRoute
  '/tenant/service-products/': typeof TenantServiceProductsIndexRoute
  '/tenant/settlement/': typeof TenantSettlementIndexRoute
  '/discover/service-products/$id/share': typeof DiscoverServiceProductsIdShareRoute
  '/discover/service-products/$id/start': typeof DiscoverServiceProductsIdStartRoute
  '/projects/$id/candidates/compare': typeof ProjectsIdCandidatesCompareRoute
  '/projects/$id/contract/$voucherId': typeof ProjectsIdContractVoucherIdRoute
  '/projects/$id/contract/tree': typeof ProjectsIdContractTreeRoute
  '/projects/$id/execution/audience': typeof ProjectsIdExecutionAudienceRoute
  '/projects/$id/execution/handoff': typeof ProjectsIdExecutionHandoffRoute
  '/projects/$id/payments/scheme': typeof ProjectsIdPaymentsSchemeRoute
  '/tenant/service-products/$id/versions': typeof TenantServiceProductsIdVersionsRoute
  '/discover/service-products/$id/': typeof DiscoverServiceProductsIdIndexRoute
  '/projects/$id/candidates/': typeof ProjectsIdCandidatesIndexRoute
  '/projects/$id/contract/': typeof ProjectsIdContractIndexRoute
  '/projects/$id/execution/': typeof ProjectsIdExecutionIndexRoute
  '/projects/$id/payments/': typeof ProjectsIdPaymentsIndexRoute
  '/tenant/service-products/$id/': typeof TenantServiceProductsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/dev-login'
    | '/gap-checklist'
    | '/guides'
    | '/m'
    | '/media-library'
    | '/snapshot'
    | '/account/data'
    | '/actor/calendar'
    | '/actor/disputes'
    | '/actor/preferences'
    | '/actor/services'
    | '/admin/attribution'
    | '/admin/incidents'
    | '/admin/permissions'
    | '/agent/memory'
    | '/h5/actor'
    | '/projects/$id'
    | '/tenant/execution'
    | '/tenant/partners'
    | '/tenant/programs'
    | '/actor/'
    | '/admin/'
    | '/agent/'
    | '/projects/'
    | '/tenant/'
    | '/admin/arbitration/$id'
    | '/admin/tenants/$id'
    | '/discover/actors/$id'
    | '/discover/cases/$id'
    | '/discover/cases/compare'
    | '/discover/programs/$id'
    | '/discover/service-products/compare'
    | '/discover/tenants/$id'
    | '/h5/tenant/msa'
    | '/plans/$id/public'
    | '/projects/$id/changes'
    | '/projects/$id/deal'
    | '/projects/$id/decision'
    | '/projects/$id/incidents'
    | '/projects/$id/messages'
    | '/projects/$id/outcome'
    | '/projects/$id/plans'
    | '/projects/$id/quote'
    | '/projects/$id/retrospective'
    | '/projects/$id/reuse'
    | '/projects/$id/review'
    | '/projects/$id/share'
    | '/projects/$id/team'
    | '/projects/$id/understand'
    | '/projects/$id/waiting'
    | '/tenant/opportunities/$id'
    | '/tenant/orders/$id'
    | '/tenant/service-products/feedback'
    | '/tenant/settlement/$month'
    | '/discover/actors/'
    | '/discover/cases/'
    | '/discover/programs/'
    | '/discover/service-products/'
    | '/projects/$id/'
    | '/tenant/orders/'
    | '/tenant/service-products/'
    | '/tenant/settlement/'
    | '/discover/service-products/$id/share'
    | '/discover/service-products/$id/start'
    | '/projects/$id/candidates/compare'
    | '/projects/$id/contract/$voucherId'
    | '/projects/$id/contract/tree'
    | '/projects/$id/execution/audience'
    | '/projects/$id/execution/handoff'
    | '/projects/$id/payments/scheme'
    | '/tenant/service-products/$id/versions'
    | '/discover/service-products/$id/'
    | '/projects/$id/candidates/'
    | '/projects/$id/contract/'
    | '/projects/$id/execution/'
    | '/projects/$id/payments/'
    | '/tenant/service-products/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/dev-login'
    | '/gap-checklist'
    | '/guides'
    | '/m'
    | '/media-library'
    | '/snapshot'
    | '/account/data'
    | '/actor/calendar'
    | '/actor/disputes'
    | '/actor/preferences'
    | '/actor/services'
    | '/admin/attribution'
    | '/admin/incidents'
    | '/admin/permissions'
    | '/agent/memory'
    | '/h5/actor'
    | '/tenant/execution'
    | '/tenant/partners'
    | '/tenant/programs'
    | '/actor'
    | '/admin'
    | '/agent'
    | '/projects'
    | '/tenant'
    | '/admin/arbitration/$id'
    | '/admin/tenants/$id'
    | '/discover/actors/$id'
    | '/discover/cases/$id'
    | '/discover/cases/compare'
    | '/discover/programs/$id'
    | '/discover/service-products/compare'
    | '/discover/tenants/$id'
    | '/h5/tenant/msa'
    | '/plans/$id/public'
    | '/projects/$id/changes'
    | '/projects/$id/deal'
    | '/projects/$id/decision'
    | '/projects/$id/incidents'
    | '/projects/$id/messages'
    | '/projects/$id/outcome'
    | '/projects/$id/plans'
    | '/projects/$id/quote'
    | '/projects/$id/retrospective'
    | '/projects/$id/reuse'
    | '/projects/$id/review'
    | '/projects/$id/share'
    | '/projects/$id/team'
    | '/projects/$id/understand'
    | '/projects/$id/waiting'
    | '/tenant/opportunities/$id'
    | '/tenant/orders/$id'
    | '/tenant/service-products/feedback'
    | '/tenant/settlement/$month'
    | '/discover/actors'
    | '/discover/cases'
    | '/discover/programs'
    | '/discover/service-products'
    | '/projects/$id'
    | '/tenant/orders'
    | '/tenant/service-products'
    | '/tenant/settlement'
    | '/discover/service-products/$id/share'
    | '/discover/service-products/$id/start'
    | '/projects/$id/candidates/compare'
    | '/projects/$id/contract/$voucherId'
    | '/projects/$id/contract/tree'
    | '/projects/$id/execution/audience'
    | '/projects/$id/execution/handoff'
    | '/projects/$id/payments/scheme'
    | '/tenant/service-products/$id/versions'
    | '/discover/service-products/$id'
    | '/projects/$id/candidates'
    | '/projects/$id/contract'
    | '/projects/$id/execution'
    | '/projects/$id/payments'
    | '/tenant/service-products/$id'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/dev-login'
    | '/gap-checklist'
    | '/guides'
    | '/m'
    | '/media-library'
    | '/snapshot'
    | '/account/data'
    | '/actor/calendar'
    | '/actor/disputes'
    | '/actor/preferences'
    | '/actor/services'
    | '/admin/attribution'
    | '/admin/incidents'
    | '/admin/permissions'
    | '/agent/memory'
    | '/h5/actor'
    | '/projects/$id'
    | '/tenant/execution'
    | '/tenant/partners'
    | '/tenant/programs'
    | '/actor/'
    | '/admin/'
    | '/agent/'
    | '/projects/'
    | '/tenant/'
    | '/admin/arbitration/$id'
    | '/admin/tenants/$id'
    | '/discover/actors/$id'
    | '/discover/cases/$id'
    | '/discover/cases/compare'
    | '/discover/programs/$id'
    | '/discover/service-products/compare'
    | '/discover/tenants/$id'
    | '/h5/tenant/msa'
    | '/plans/$id/public'
    | '/projects/$id/changes'
    | '/projects/$id/deal'
    | '/projects/$id/decision'
    | '/projects/$id/incidents'
    | '/projects/$id/messages'
    | '/projects/$id/outcome'
    | '/projects/$id/plans'
    | '/projects/$id/quote'
    | '/projects/$id/retrospective'
    | '/projects/$id/reuse'
    | '/projects/$id/review'
    | '/projects/$id/share'
    | '/projects/$id/team'
    | '/projects/$id/understand'
    | '/projects/$id/waiting'
    | '/tenant/opportunities/$id'
    | '/tenant/orders/$id'
    | '/tenant/service-products/feedback'
    | '/tenant/settlement/$month'
    | '/discover/actors/'
    | '/discover/cases/'
    | '/discover/programs/'
    | '/discover/service-products/'
    | '/projects/$id/'
    | '/tenant/orders/'
    | '/tenant/service-products/'
    | '/tenant/settlement/'
    | '/discover/service-products/$id/share'
    | '/discover/service-products/$id/start'
    | '/projects/$id/candidates/compare'
    | '/projects/$id/contract/$voucherId'
    | '/projects/$id/contract/tree'
    | '/projects/$id/execution/audience'
    | '/projects/$id/execution/handoff'
    | '/projects/$id/payments/scheme'
    | '/tenant/service-products/$id/versions'
    | '/discover/service-products/$id/'
    | '/projects/$id/candidates/'
    | '/projects/$id/contract/'
    | '/projects/$id/execution/'
    | '/projects/$id/payments/'
    | '/tenant/service-products/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DevLoginRoute: typeof DevLoginRoute
  GapChecklistRoute: typeof GapChecklistRoute
  GuidesRoute: typeof GuidesRoute
  MRoute: typeof MRoute
  MediaLibraryRoute: typeof MediaLibraryRoute
  SnapshotRoute: typeof SnapshotRoute
  AccountDataRoute: typeof AccountDataRoute
  ActorCalendarRoute: typeof ActorCalendarRoute
  ActorDisputesRoute: typeof ActorDisputesRoute
  ActorPreferencesRoute: typeof ActorPreferencesRoute
  ActorServicesRoute: typeof ActorServicesRoute
  AdminAttributionRoute: typeof AdminAttributionRoute
  AdminIncidentsRoute: typeof AdminIncidentsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AgentMemoryRoute: typeof AgentMemoryRoute
  H5ActorRoute: typeof H5ActorRoute
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  TenantExecutionRoute: typeof TenantExecutionRoute
  TenantPartnersRoute: typeof TenantPartnersRoute
  TenantProgramsRoute: typeof TenantProgramsRoute
  ActorIndexRoute: typeof ActorIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentIndexRoute: typeof AgentIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TenantIndexRoute: typeof TenantIndexRoute
  AdminArbitrationIdRoute: typeof AdminArbitrationIdRoute
  AdminTenantsIdRoute: typeof AdminTenantsIdRoute
  DiscoverActorsIdRoute: typeof DiscoverActorsIdRoute
  DiscoverCasesIdRoute: typeof DiscoverCasesIdRoute
  DiscoverCasesCompareRoute: typeof DiscoverCasesCompareRoute
  DiscoverProgramsIdRoute: typeof DiscoverProgramsIdRoute
  DiscoverServiceProductsCompareRoute: typeof DiscoverServiceProductsCompareRoute
  DiscoverTenantsIdRoute: typeof DiscoverTenantsIdRoute
  H5TenantMsaRoute: typeof H5TenantMsaRoute
  PlansIdPublicRoute: typeof PlansIdPublicRoute
  TenantOpportunitiesIdRoute: typeof TenantOpportunitiesIdRoute
  TenantOrdersIdRoute: typeof TenantOrdersIdRoute
  TenantServiceProductsFeedbackRoute: typeof TenantServiceProductsFeedbackRoute
  TenantSettlementMonthRoute: typeof TenantSettlementMonthRoute
  DiscoverActorsIndexRoute: typeof DiscoverActorsIndexRoute
  DiscoverCasesIndexRoute: typeof DiscoverCasesIndexRoute
  DiscoverProgramsIndexRoute: typeof DiscoverProgramsIndexRoute
  DiscoverServiceProductsIndexRoute: typeof DiscoverServiceProductsIndexRoute
  TenantOrdersIndexRoute: typeof TenantOrdersIndexRoute
  TenantServiceProductsIndexRoute: typeof TenantServiceProductsIndexRoute
  TenantSettlementIndexRoute: typeof TenantSettlementIndexRoute
  DiscoverServiceProductsIdShareRoute: typeof DiscoverServiceProductsIdShareRoute
  DiscoverServiceProductsIdStartRoute: typeof DiscoverServiceProductsIdStartRoute
  TenantServiceProductsIdVersionsRoute: typeof TenantServiceProductsIdVersionsRoute
  DiscoverServiceProductsIdIndexRoute: typeof DiscoverServiceProductsIdIndexRoute
  TenantServiceProductsIdIndexRoute: typeof TenantServiceProductsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/snapshot': {
      id: '/snapshot'
      path: '/snapshot'
      fullPath: '/snapshot'
      preLoaderRoute: typeof SnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-library': {
      id: '/media-library'
      path: '/media-library'
      fullPath: '/media-library'
      preLoaderRoute: typeof MediaLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gap-checklist': {
      id: '/gap-checklist'
      path: '/gap-checklist'
      fullPath: '/gap-checklist'
      preLoaderRoute: typeof GapChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actor/': {
      id: '/actor/'
      path: '/actor'
      fullPath: '/actor/'
      preLoaderRoute: typeof ActorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/programs': {
      id: '/tenant/programs'
      path: '/tenant/programs'
      fullPath: '/tenant/programs'
      preLoaderRoute: typeof TenantProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/partners': {
      id: '/tenant/partners'
      path: '/tenant/partners'
      fullPath: '/tenant/partners'
      preLoaderRoute: typeof TenantPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/execution': {
      id: '/tenant/execution'
      path: '/tenant/execution'
      fullPath: '/tenant/execution'
      preLoaderRoute: typeof TenantExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h5/actor': {
      id: '/h5/actor'
      path: '/h5/actor'
      fullPath: '/h5/actor'
      preLoaderRoute: typeof H5ActorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/memory': {
      id: '/agent/memory'
      path: '/agent/memory'
      fullPath: '/agent/memory'
      preLoaderRoute: typeof AgentMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/incidents': {
      id: '/admin/incidents'
      path: '/admin/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AdminIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attribution': {
      id: '/admin/attribution'
      path: '/admin/attribution'
      fullPath: '/admin/attribution'
      preLoaderRoute: typeof AdminAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actor/services': {
      id: '/actor/services'
      path: '/actor/services'
      fullPath: '/actor/services'
      preLoaderRoute: typeof ActorServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actor/preferences': {
      id: '/actor/preferences'
      path: '/actor/preferences'
      fullPath: '/actor/preferences'
      preLoaderRoute: typeof ActorPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actor/disputes': {
      id: '/actor/disputes'
      path: '/actor/disputes'
      fullPath: '/actor/disputes'
      preLoaderRoute: typeof ActorDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actor/calendar': {
      id: '/actor/calendar'
      path: '/actor/calendar'
      fullPath: '/actor/calendar'
      preLoaderRoute: typeof ActorCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/data': {
      id: '/account/data'
      path: '/account/data'
      fullPath: '/account/data'
      preLoaderRoute: typeof AccountDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/settlement/': {
      id: '/tenant/settlement/'
      path: '/tenant/settlement'
      fullPath: '/tenant/settlement/'
      preLoaderRoute: typeof TenantSettlementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/service-products/': {
      id: '/tenant/service-products/'
      path: '/tenant/service-products'
      fullPath: '/tenant/service-products/'
      preLoaderRoute: typeof TenantServiceProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/orders/': {
      id: '/tenant/orders/'
      path: '/tenant/orders'
      fullPath: '/tenant/orders/'
      preLoaderRoute: typeof TenantOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/discover/service-products/': {
      id: '/discover/service-products/'
      path: '/discover/service-products'
      fullPath: '/discover/service-products/'
      preLoaderRoute: typeof DiscoverServiceProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/programs/': {
      id: '/discover/programs/'
      path: '/discover/programs'
      fullPath: '/discover/programs/'
      preLoaderRoute: typeof DiscoverProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/cases/': {
      id: '/discover/cases/'
      path: '/discover/cases'
      fullPath: '/discover/cases/'
      preLoaderRoute: typeof DiscoverCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/actors/': {
      id: '/discover/actors/'
      path: '/discover/actors'
      fullPath: '/discover/actors/'
      preLoaderRoute: typeof DiscoverActorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/settlement/$month': {
      id: '/tenant/settlement/$month'
      path: '/tenant/settlement/$month'
      fullPath: '/tenant/settlement/$month'
      preLoaderRoute: typeof TenantSettlementMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/service-products/feedback': {
      id: '/tenant/service-products/feedback'
      path: '/tenant/service-products/feedback'
      fullPath: '/tenant/service-products/feedback'
      preLoaderRoute: typeof TenantServiceProductsFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/orders/$id': {
      id: '/tenant/orders/$id'
      path: '/tenant/orders/$id'
      fullPath: '/tenant/orders/$id'
      preLoaderRoute: typeof TenantOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/opportunities/$id': {
      id: '/tenant/opportunities/$id'
      path: '/tenant/opportunities/$id'
      fullPath: '/tenant/opportunities/$id'
      preLoaderRoute: typeof TenantOpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/waiting': {
      id: '/projects/$id/waiting'
      path: '/waiting'
      fullPath: '/projects/$id/waiting'
      preLoaderRoute: typeof ProjectsIdWaitingRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/understand': {
      id: '/projects/$id/understand'
      path: '/understand'
      fullPath: '/projects/$id/understand'
      preLoaderRoute: typeof ProjectsIdUnderstandRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/team': {
      id: '/projects/$id/team'
      path: '/team'
      fullPath: '/projects/$id/team'
      preLoaderRoute: typeof ProjectsIdTeamRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/share': {
      id: '/projects/$id/share'
      path: '/share'
      fullPath: '/projects/$id/share'
      preLoaderRoute: typeof ProjectsIdShareRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/review': {
      id: '/projects/$id/review'
      path: '/review'
      fullPath: '/projects/$id/review'
      preLoaderRoute: typeof ProjectsIdReviewRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/reuse': {
      id: '/projects/$id/reuse'
      path: '/reuse'
      fullPath: '/projects/$id/reuse'
      preLoaderRoute: typeof ProjectsIdReuseRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/retrospective': {
      id: '/projects/$id/retrospective'
      path: '/retrospective'
      fullPath: '/projects/$id/retrospective'
      preLoaderRoute: typeof ProjectsIdRetrospectiveRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/quote': {
      id: '/projects/$id/quote'
      path: '/quote'
      fullPath: '/projects/$id/quote'
      preLoaderRoute: typeof ProjectsIdQuoteRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/plans': {
      id: '/projects/$id/plans'
      path: '/plans'
      fullPath: '/projects/$id/plans'
      preLoaderRoute: typeof ProjectsIdPlansRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/outcome': {
      id: '/projects/$id/outcome'
      path: '/outcome'
      fullPath: '/projects/$id/outcome'
      preLoaderRoute: typeof ProjectsIdOutcomeRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/messages': {
      id: '/projects/$id/messages'
      path: '/messages'
      fullPath: '/projects/$id/messages'
      preLoaderRoute: typeof ProjectsIdMessagesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/incidents': {
      id: '/projects/$id/incidents'
      path: '/incidents'
      fullPath: '/projects/$id/incidents'
      preLoaderRoute: typeof ProjectsIdIncidentsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/decision': {
      id: '/projects/$id/decision'
      path: '/decision'
      fullPath: '/projects/$id/decision'
      preLoaderRoute: typeof ProjectsIdDecisionRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/deal': {
      id: '/projects/$id/deal'
      path: '/deal'
      fullPath: '/projects/$id/deal'
      preLoaderRoute: typeof ProjectsIdDealRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/changes': {
      id: '/projects/$id/changes'
      path: '/changes'
      fullPath: '/projects/$id/changes'
      preLoaderRoute: typeof ProjectsIdChangesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/plans/$id/public': {
      id: '/plans/$id/public'
      path: '/plans/$id/public'
      fullPath: '/plans/$id/public'
      preLoaderRoute: typeof PlansIdPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h5/tenant/msa': {
      id: '/h5/tenant/msa'
      path: '/h5/tenant/msa'
      fullPath: '/h5/tenant/msa'
      preLoaderRoute: typeof H5TenantMsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/tenants/$id': {
      id: '/discover/tenants/$id'
      path: '/discover/tenants/$id'
      fullPath: '/discover/tenants/$id'
      preLoaderRoute: typeof DiscoverTenantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/service-products/compare': {
      id: '/discover/service-products/compare'
      path: '/discover/service-products/compare'
      fullPath: '/discover/service-products/compare'
      preLoaderRoute: typeof DiscoverServiceProductsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/programs/$id': {
      id: '/discover/programs/$id'
      path: '/discover/programs/$id'
      fullPath: '/discover/programs/$id'
      preLoaderRoute: typeof DiscoverProgramsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/cases/compare': {
      id: '/discover/cases/compare'
      path: '/discover/cases/compare'
      fullPath: '/discover/cases/compare'
      preLoaderRoute: typeof DiscoverCasesCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/cases/$id': {
      id: '/discover/cases/$id'
      path: '/discover/cases/$id'
      fullPath: '/discover/cases/$id'
      preLoaderRoute: typeof DiscoverCasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/actors/$id': {
      id: '/discover/actors/$id'
      path: '/discover/actors/$id'
      fullPath: '/discover/actors/$id'
      preLoaderRoute: typeof DiscoverActorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants/$id': {
      id: '/admin/tenants/$id'
      path: '/admin/tenants/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AdminTenantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/arbitration/$id': {
      id: '/admin/arbitration/$id'
      path: '/admin/arbitration/$id'
      fullPath: '/admin/arbitration/$id'
      preLoaderRoute: typeof AdminArbitrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/service-products/$id/': {
      id: '/tenant/service-products/$id/'
      path: '/tenant/service-products/$id'
      fullPath: '/tenant/service-products/$id/'
      preLoaderRoute: typeof TenantServiceProductsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/payments/': {
      id: '/projects/$id/payments/'
      path: '/payments'
      fullPath: '/projects/$id/payments/'
      preLoaderRoute: typeof ProjectsIdPaymentsIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/execution/': {
      id: '/projects/$id/execution/'
      path: '/execution'
      fullPath: '/projects/$id/execution/'
      preLoaderRoute: typeof ProjectsIdExecutionIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/contract/': {
      id: '/projects/$id/contract/'
      path: '/contract'
      fullPath: '/projects/$id/contract/'
      preLoaderRoute: typeof ProjectsIdContractIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/candidates/': {
      id: '/projects/$id/candidates/'
      path: '/candidates'
      fullPath: '/projects/$id/candidates/'
      preLoaderRoute: typeof ProjectsIdCandidatesIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/discover/service-products/$id/': {
      id: '/discover/service-products/$id/'
      path: '/discover/service-products/$id'
      fullPath: '/discover/service-products/$id/'
      preLoaderRoute: typeof DiscoverServiceProductsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/service-products/$id/versions': {
      id: '/tenant/service-products/$id/versions'
      path: '/tenant/service-products/$id/versions'
      fullPath: '/tenant/service-products/$id/versions'
      preLoaderRoute: typeof TenantServiceProductsIdVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/payments/scheme': {
      id: '/projects/$id/payments/scheme'
      path: '/payments/scheme'
      fullPath: '/projects/$id/payments/scheme'
      preLoaderRoute: typeof ProjectsIdPaymentsSchemeRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/execution/handoff': {
      id: '/projects/$id/execution/handoff'
      path: '/execution/handoff'
      fullPath: '/projects/$id/execution/handoff'
      preLoaderRoute: typeof ProjectsIdExecutionHandoffRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/execution/audience': {
      id: '/projects/$id/execution/audience'
      path: '/execution/audience'
      fullPath: '/projects/$id/execution/audience'
      preLoaderRoute: typeof ProjectsIdExecutionAudienceRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/contract/tree': {
      id: '/projects/$id/contract/tree'
      path: '/contract/tree'
      fullPath: '/projects/$id/contract/tree'
      preLoaderRoute: typeof ProjectsIdContractTreeRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/contract/$voucherId': {
      id: '/projects/$id/contract/$voucherId'
      path: '/contract/$voucherId'
      fullPath: '/projects/$id/contract/$voucherId'
      preLoaderRoute: typeof ProjectsIdContractVoucherIdRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/candidates/compare': {
      id: '/projects/$id/candidates/compare'
      path: '/candidates/compare'
      fullPath: '/projects/$id/candidates/compare'
      preLoaderRoute: typeof ProjectsIdCandidatesCompareRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/discover/service-products/$id/start': {
      id: '/discover/service-products/$id/start'
      path: '/discover/service-products/$id/start'
      fullPath: '/discover/service-products/$id/start'
      preLoaderRoute: typeof DiscoverServiceProductsIdStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/service-products/$id/share': {
      id: '/discover/service-products/$id/share'
      path: '/discover/service-products/$id/share'
      fullPath: '/discover/service-products/$id/share'
      preLoaderRoute: typeof DiscoverServiceProductsIdShareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsIdRouteChildren {
  ProjectsIdChangesRoute: typeof ProjectsIdChangesRoute
  ProjectsIdDealRoute: typeof ProjectsIdDealRoute
  ProjectsIdDecisionRoute: typeof ProjectsIdDecisionRoute
  ProjectsIdIncidentsRoute: typeof ProjectsIdIncidentsRoute
  ProjectsIdMessagesRoute: typeof ProjectsIdMessagesRoute
  ProjectsIdOutcomeRoute: typeof ProjectsIdOutcomeRoute
  ProjectsIdPlansRoute: typeof ProjectsIdPlansRoute
  ProjectsIdQuoteRoute: typeof ProjectsIdQuoteRoute
  ProjectsIdRetrospectiveRoute: typeof ProjectsIdRetrospectiveRoute
  ProjectsIdReuseRoute: typeof ProjectsIdReuseRoute
  ProjectsIdReviewRoute: typeof ProjectsIdReviewRoute
  ProjectsIdShareRoute: typeof ProjectsIdShareRoute
  ProjectsIdTeamRoute: typeof ProjectsIdTeamRoute
  ProjectsIdUnderstandRoute: typeof ProjectsIdUnderstandRoute
  ProjectsIdWaitingRoute: typeof ProjectsIdWaitingRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
  ProjectsIdCandidatesCompareRoute: typeof ProjectsIdCandidatesCompareRoute
  ProjectsIdContractVoucherIdRoute: typeof ProjectsIdContractVoucherIdRoute
  ProjectsIdContractTreeRoute: typeof ProjectsIdContractTreeRoute
  ProjectsIdExecutionAudienceRoute: typeof ProjectsIdExecutionAudienceRoute
  ProjectsIdExecutionHandoffRoute: typeof ProjectsIdExecutionHandoffRoute
  ProjectsIdPaymentsSchemeRoute: typeof ProjectsIdPaymentsSchemeRoute
  ProjectsIdCandidatesIndexRoute: typeof ProjectsIdCandidatesIndexRoute
  ProjectsIdContractIndexRoute: typeof ProjectsIdContractIndexRoute
  ProjectsIdExecutionIndexRoute: typeof ProjectsIdExecutionIndexRoute
  ProjectsIdPaymentsIndexRoute: typeof ProjectsIdPaymentsIndexRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdChangesRoute: ProjectsIdChangesRoute,
  ProjectsIdDealRoute: ProjectsIdDealRoute,
  ProjectsIdDecisionRoute: ProjectsIdDecisionRoute,
  ProjectsIdIncidentsRoute: ProjectsIdIncidentsRoute,
  ProjectsIdMessagesRoute: ProjectsIdMessagesRoute,
  ProjectsIdOutcomeRoute: ProjectsIdOutcomeRoute,
  ProjectsIdPlansRoute: ProjectsIdPlansRoute,
  ProjectsIdQuoteRoute: ProjectsIdQuoteRoute,
  ProjectsIdRetrospectiveRoute: ProjectsIdRetrospectiveRoute,
  ProjectsIdReuseRoute: ProjectsIdReuseRoute,
  ProjectsIdReviewRoute: ProjectsIdReviewRoute,
  ProjectsIdShareRoute: ProjectsIdShareRoute,
  ProjectsIdTeamRoute: ProjectsIdTeamRoute,
  ProjectsIdUnderstandRoute: ProjectsIdUnderstandRoute,
  ProjectsIdWaitingRoute: ProjectsIdWaitingRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
  ProjectsIdCandidatesCompareRoute: ProjectsIdCandidatesCompareRoute,
  ProjectsIdContractVoucherIdRoute: ProjectsIdContractVoucherIdRoute,
  ProjectsIdContractTreeRoute: ProjectsIdContractTreeRoute,
  ProjectsIdExecutionAudienceRoute: ProjectsIdExecutionAudienceRoute,
  ProjectsIdExecutionHandoffRoute: ProjectsIdExecutionHandoffRoute,
  ProjectsIdPaymentsSchemeRoute: ProjectsIdPaymentsSchemeRoute,
  ProjectsIdCandidatesIndexRoute: ProjectsIdCandidatesIndexRoute,
  ProjectsIdContractIndexRoute: ProjectsIdContractIndexRoute,
  ProjectsIdExecutionIndexRoute: ProjectsIdExecutionIndexRoute,
  ProjectsIdPaymentsIndexRoute: ProjectsIdPaymentsIndexRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DevLoginRoute: DevLoginRoute,
  GapChecklistRoute: GapChecklistRoute,
  GuidesRoute: GuidesRoute,
  MRoute: MRoute,
  MediaLibraryRoute: MediaLibraryRoute,
  SnapshotRoute: SnapshotRoute,
  AccountDataRoute: AccountDataRoute,
  ActorCalendarRoute: ActorCalendarRoute,
  ActorDisputesRoute: ActorDisputesRoute,
  ActorPreferencesRoute: ActorPreferencesRoute,
  ActorServicesRoute: ActorServicesRoute,
  AdminAttributionRoute: AdminAttributionRoute,
  AdminIncidentsRoute: AdminIncidentsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AgentMemoryRoute: AgentMemoryRoute,
  H5ActorRoute: H5ActorRoute,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  TenantExecutionRoute: TenantExecutionRoute,
  TenantPartnersRoute: TenantPartnersRoute,
  TenantProgramsRoute: TenantProgramsRoute,
  ActorIndexRoute: ActorIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentIndexRoute: AgentIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TenantIndexRoute: TenantIndexRoute,
  AdminArbitrationIdRoute: AdminArbitrationIdRoute,
  AdminTenantsIdRoute: AdminTenantsIdRoute,
  DiscoverActorsIdRoute: DiscoverActorsIdRoute,
  DiscoverCasesIdRoute: DiscoverCasesIdRoute,
  DiscoverCasesCompareRoute: DiscoverCasesCompareRoute,
  DiscoverProgramsIdRoute: DiscoverProgramsIdRoute,
  DiscoverServiceProductsCompareRoute: DiscoverServiceProductsCompareRoute,
  DiscoverTenantsIdRoute: DiscoverTenantsIdRoute,
  H5TenantMsaRoute: H5TenantMsaRoute,
  PlansIdPublicRoute: PlansIdPublicRoute,
  TenantOpportunitiesIdRoute: TenantOpportunitiesIdRoute,
  TenantOrdersIdRoute: TenantOrdersIdRoute,
  TenantServiceProductsFeedbackRoute: TenantServiceProductsFeedbackRoute,
  TenantSettlementMonthRoute: TenantSettlementMonthRoute,
  DiscoverActorsIndexRoute: DiscoverActorsIndexRoute,
  DiscoverCasesIndexRoute: DiscoverCasesIndexRoute,
  DiscoverProgramsIndexRoute: DiscoverProgramsIndexRoute,
  DiscoverServiceProductsIndexRoute: DiscoverServiceProductsIndexRoute,
  TenantOrdersIndexRoute: TenantOrdersIndexRoute,
  TenantServiceProductsIndexRoute: TenantServiceProductsIndexRoute,
  TenantSettlementIndexRoute: TenantSettlementIndexRoute,
  DiscoverServiceProductsIdShareRoute: DiscoverServiceProductsIdShareRoute,
  DiscoverServiceProductsIdStartRoute: DiscoverServiceProductsIdStartRoute,
  TenantServiceProductsIdVersionsRoute: TenantServiceProductsIdVersionsRoute,
  DiscoverServiceProductsIdIndexRoute: DiscoverServiceProductsIdIndexRoute,
  TenantServiceProductsIdIndexRoute: TenantServiceProductsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
