/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as MDemandsNewRouteImport } from './routes/m.demands.new'
import { Route as MActorsActorIdRouteImport } from './routes/m.actors.$actorId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as SupplierDemandsDemandIdBriefRouteImport } from './routes/supplier.demands.$demandId.brief'
import { Route as MDemandsDemandIdBriefRouteImport } from './routes/m.demands.$demandId.brief'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const MDemandsNewRoute = MDemandsNewRouteImport.update({
  id: '/m/demands/new',
  path: '/m/demands/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MActorsActorIdRoute = MActorsActorIdRouteImport.update({
  id: '/m/actors/$actorId',
  path: '/m/actors/$actorId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierDemandsDemandIdBriefRoute =
  SupplierDemandsDemandIdBriefRouteImport.update({
    id: '/supplier/demands/$demandId/brief',
    path: '/supplier/demands/$demandId/brief',
    getParentRoute: () => rootRouteImport,
  } as any)
const MDemandsDemandIdBriefRoute = MDemandsDemandIdBriefRouteImport.update({
  id: '/m/demands/$demandId/brief',
  path: '/m/demands/$demandId/brief',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/m/actors/$actorId': typeof MActorsActorIdRoute
  '/m/demands/new': typeof MDemandsNewRoute
  '/m/demands/$demandId/brief': typeof MDemandsDemandIdBriefRoute
  '/supplier/demands/$demandId/brief': typeof SupplierDemandsDemandIdBriefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/m/actors/$actorId': typeof MActorsActorIdRoute
  '/m/demands/new': typeof MDemandsNewRoute
  '/m/demands/$demandId/brief': typeof MDemandsDemandIdBriefRoute
  '/supplier/demands/$demandId/brief': typeof SupplierDemandsDemandIdBriefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/m/actors/$actorId': typeof MActorsActorIdRoute
  '/m/demands/new': typeof MDemandsNewRoute
  '/m/demands/$demandId/brief': typeof MDemandsDemandIdBriefRoute
  '/supplier/demands/$demandId/brief': typeof SupplierDemandsDemandIdBriefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/m/actors/$actorId'
    | '/m/demands/new'
    | '/m/demands/$demandId/brief'
    | '/supplier/demands/$demandId/brief'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/m/actors/$actorId'
    | '/m/demands/new'
    | '/m/demands/$demandId/brief'
    | '/supplier/demands/$demandId/brief'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/m/actors/$actorId'
    | '/m/demands/new'
    | '/m/demands/$demandId/brief'
    | '/supplier/demands/$demandId/brief'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  MActorsActorIdRoute: typeof MActorsActorIdRoute
  MDemandsNewRoute: typeof MDemandsNewRoute
  MDemandsDemandIdBriefRoute: typeof MDemandsDemandIdBriefRoute
  SupplierDemandsDemandIdBriefRoute: typeof SupplierDemandsDemandIdBriefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/demands/new': {
      id: '/m/demands/new'
      path: '/m/demands/new'
      fullPath: '/m/demands/new'
      preLoaderRoute: typeof MDemandsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/actors/$actorId': {
      id: '/m/actors/$actorId'
      path: '/m/actors/$actorId'
      fullPath: '/m/actors/$actorId'
      preLoaderRoute: typeof MActorsActorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/demands/$demandId/brief': {
      id: '/supplier/demands/$demandId/brief'
      path: '/supplier/demands/$demandId/brief'
      fullPath: '/supplier/demands/$demandId/brief'
      preLoaderRoute: typeof SupplierDemandsDemandIdBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/demands/$demandId/brief': {
      id: '/m/demands/$demandId/brief'
      path: '/m/demands/$demandId/brief'
      fullPath: '/m/demands/$demandId/brief'
      preLoaderRoute: typeof MDemandsDemandIdBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  MActorsActorIdRoute: MActorsActorIdRoute,
  MDemandsNewRoute: MDemandsNewRoute,
  MDemandsDemandIdBriefRoute: MDemandsDemandIdBriefRoute,
  SupplierDemandsDemandIdBriefRoute: SupplierDemandsDemandIdBriefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
